# Importing Library

In [6]:
#Importing Alpha_Vantage Library For Downloading Stock Data
from alpha_vantage.timeseries import TimeSeries
#Importing Pandas To perform ETL Operation On Stock Data
import pandas as pd

# Retrieving stock data using API

In [2]:
#Using Alpha_Vantage API's to call stock data
ts = TimeSeries(key = 'UGXITKR3V1V5SCNT', output_format = 'pandas')
#Downloading Stock Data of target company i.e. GoldmnanSachs and its compeititors
GS_data, GS_meta = ts.get_daily_adjusted(symbol = 'GS', outputsize = 'full')
MS_data, MS_meta = ts.get_daily_adjusted(symbol = 'MS', outputsize = 'full')
JPM_data, JPM_meta = ts.get_daily_adjusted(symbol = 'JPM', outputsize = 'full')
WFC_data, WFC_meta = ts.get_daily_adjusted(symbol = 'WFC', outputsize = 'full')
C_data, C_meta = ts.get_daily_adjusted(symbol = 'C', outputsize = 'full')

In [3]:
BAC_data, BAC_meta = ts.get_daily_adjusted(symbol = 'BAC', outputsize = 'full')

In [4]:
#Renaming data colunms to improve clarity of Data to layman
GS_data.rename(columns={'1. open': 'GS_open', '2. high': 'GS_high', '3. low': 'GS_low', '4. close': 'GS_close', '5. adjusted close':'GS_aclose', '6. volume': 'GS_volume'},inplace = True)
MS_data.rename(columns={'1. open': 'MS_open', '2. high': 'MS_high', '3. low': 'MS_low', '4. close': 'MS_close', '5. adjusted close':'MS_aclose', '6. volume': 'MS_volume'},inplace = True)
JPM_data.rename(columns={'1. open': 'JPM_open', '2. high': 'JPM_high', '3. low': 'JPM_low', '4. close': 'JPM_close', '5. adjusted close':'JPM_aclose', '6. volume': 'JPM_volume'},inplace = True)
WFC_data.rename(columns={'1. open': 'WFC_open', '2. high': 'WFC_high', '3. low': 'WFC_low', '4. close': 'WFC_close', '5. adjusted close':'WFC_aclose', '6. volume': 'WFC_volume'},inplace = True)
C_data.rename(columns={'1. open': 'C_open', '2. high': 'C_high', '3. low': 'C_low', '4. close': 'C_close', '5. adjusted close':'C_aclose', '6. volume': 'C_volume'},inplace = True)
BAC_data.rename(columns={'1. open': 'BAC_open', '2. high': 'BAC_high', '3. low': 'BAC_low', '4. close': 'BAC_close', '5. adjusted close':'BAC_aclose', '6. volume': 'BAC_volume'},inplace = True)

In [5]:
#Removing useless colunms as they don't affect the price of Goldmam Sachs Stocks
GS_data = GS_data.drop(columns = ['7. dividend amount', '8. split coefficient'])
MS_data = MS_data.drop(columns = ['7. dividend amount', '8. split coefficient'])
JPM_data = JPM_data.drop(columns = ['7. dividend amount', '8. split coefficient'])
WFC_data = WFC_data.drop(columns = ['7. dividend amount', '8. split coefficient'])
C_data = C_data.drop(columns = ['7. dividend amount', '8. split coefficient'])
BAC_data = BAC_data.drop(columns = ['7. dividend amount', '8. split coefficient'])

# Concating all data

In [7]:
#Concating all the data to create a common datasheet
trial_data = pd.concat([GS_data,MS_data,JPM_data,WFC_data,C_data,BAC_data], axis=1)

In [8]:
trial_data.head()

,GS_open,GS_high,GS_low,GS_close,GS_aclose,GS_volume,MS_open,MS_high,MS_low,MS_close,...,C_low,C_close,C_aclose,C_volume,BAC_open,BAC_high,BAC_low,BAC_close,BAC_aclose,BAC_volume
date,,,,,,,,,,,,,,,,,,,,,
2021-04-30,351.12,352.8197,347.20,348.45,348.45,2101069.0,82.89,83.2800,82.23,82.55,...,71.0900,71.24,71.240000,23669327.0,40.84,40.900,40.470,40.53,40.53,39203386.0
2021-04-29,350.55,353.8300,347.48,352.97,352.97,2584423.0,83.20,83.7900,82.13,83.64,...,72.8807,73.84,73.315144,20628360.0,40.55,41.130,40.460,41.11,41.11,44008650.0
2021-04-28,348.00,350.1200,346.09,348.11,348.11,2140875.0,82.40,82.9500,82.07,82.73,...,72.7300,72.91,72.391755,14420387.0,39.93,40.220,39.880,40.03,40.03,34084387.0
2021-04-27,344.00,347.5500,343.66,346.63,346.63,2088604.0,81.41,82.0500,81.20,81.96,...,72.3600,72.99,72.471186,13357476.0,39.67,39.920,39.510,39.88,39.88,34304845.0
2021-04-26,341.94,345.9000,340.89,343.52,343.52,2171458.0,81.81,82.4232,81.38,81.52,...,71.6100,72.20,71.686801,13098596.0,39.35,39.845,39.285,39.41,39.41,34699774.0

# Sorting data and saving in CSV file

In [13]:
#Sorting The GoldmanSachs StockData in Ascending_Order
trial_data = trial_data.sort_index(axis = 0, ascending = True)

In [14]:
trial_data.head()

,GS_open,GS_high,GS_low,GS_close,GS_aclose,GS_volume,MS_open,MS_high,MS_low,MS_close,...,C_low,C_close,C_aclose,C_volume,BAC_open,BAC_high,BAC_low,BAC_close,BAC_aclose,BAC_volume
date,,,,,,,,,,,,,,,,,,,,,
1999-11-01,70.50,71.00,69.31,69.38,54.147797,949300.0,110.00,112.62,109.12,110.62,...,53.06,53.38,246.933644,11062500.0,64.50,65.19,63.94,64.87,17.647758,4018200.0
1999-11-02,69.19,71.75,69.13,69.75,54.436564,543000.0,110.62,113.06,109.75,110.12,...,53.38,53.69,248.367691,11400000.0,64.94,65.75,64.19,64.25,17.479088,3909800.0
1999-11-03,69.81,69.88,68.31,68.75,53.656112,924000.0,110.12,110.12,107.69,108.88,...,52.69,53.00,245.175780,12225750.0,64.75,64.75,62.94,63.00,17.139028,4876700.0
1999-11-04,69.69,70.75,69.44,70.13,54.733136,570400.0,110.19,113.75,110.00,113.19,...,53.06,54.75,253.271206,53848500.0,63.88,64.50,63.50,63.50,17.275052,5136800.0
1999-11-05,72.00,74.31,71.25,73.69,57.511547,1304900.0,116.12,117.38,115.25,115.81,...,54.00,54.38,251.559602,13857000.0,65.50,66.87,65.00,65.06,17.699447,4981800.0

In [16]:
#Deleting first 33 rows as the, 
#Data points for each every data attributes like technical indicators exist from this dates.
trial_data = trial_data.iloc[33:]

In [17]:
trial_data.to_csv('initial_data3.csv')